<?php include_once(__DIR__ . '/../header.php'); ?>
    <div id="content">
        <h1>Condiciones Generales de Compra</h1>
        <h2>1. Partes</h2>
        <p>1.1. Estas Condiciones Generales de Compra son suscritas, de una parte, por SOL DE MARZO, S.L., con NIF A12345678 y domicilio en Madrid, Calle de Gabriel Usera 54, Oficina 1. 28026 (en adelante, Sol de Marzo), titular de la p&aacute;gina web llamada Sol de Marzo (en adelante, Sol de Marzo), y, de otra, por el Comprador, entendido como el usuario de Sol de Marzo que complete todos los pasos de la web para la compra de alg&uacute;n producto ofrecido en la misma, incluida la aceptaci&oacute;n de estas Condiciones Generales de Compra.</p>
        <p>1.2. Sol de Marzo se configura en el mercado a los efectos de transacciones econ&oacute;micas como un intermediario entre el usuario Comprador y el Vendedor, entendido como la persona natural o jur&iacute;dica con quien Sol de Marzo hubiera alcanzado un acuerdo comercial que le permite la oferta y venta de productos a trav&eacute;s de la web. Adem&aacute;s, estas Condiciones afectan al Vendedor o Vendedores que hubieran publicado en Sol de Marzo los productos que conforman el pedido del Comprador.</p>
        <h2>2. Objeto</h2>
        <p>El objeto de estas Condiciones es regular la adquisici&oacute;n de productos a trav&eacute;s de Sol de Marzo por parte del Comprador, de entre todos los ofrecidos en la web por los Vendedores registrados en la misma.</p>
        <h2>3. Aceptaci&oacute;n</h2>
        <p>3.1. Se entiende que el Comprador acepta sin reserva las presentes Condiciones Generales de Compra cuando, al final del proceso de compra, marque la casilla de verificaci&oacute;n destinada a aceptarlas.</p>
        <p>3.2. Estas Condiciones Generales de Compra han de ser completadas con las Condiciones Particulares impuestas por cada Vendedor para la compra de cada uno de los productos que ofrece, las cuales se entienden aceptadas junto con aqu&eacute;llas. De esta forma, ser&aacute;n de aplicaci&oacute;n tantas Condiciones Particulares como productos sean objeto de pedido por parte del Comprador.</p>
        <p>3.3. Las Condiciones Particulares de cada producto son mostradas antes de finalizar el proceso de compra y aceptar estas Condiciones y, sin &aacute;nimo de exhaustividad, comprenden: el nombre y descripci&oacute;n del producto, su precio, la forma de env&iacute;o y el precio que corresponde, las condiciones para desistir de la compra del producto, las garant&iacute;as contractuales y servicios posventa que se indiquen, etc.</p>
        <h2>4. Informaci&oacute;n y precios</h2>
        <p>4.1. Tanto la informaci&oacute;n acerca de los Vendedores como sobre los productos por ellos ofrecidos es directamente publicada por los Vendedores.</p>
        <p>4.2. Sol de Marzo trata de que toda la informaci&oacute;n publicada en Sol de Marzo sea real y precisa, pues todos los Vendedores tienen la expresa obligaci&oacute;n de mostrar las caracter&iacute;sticas y propiedades de los productos que se ofertan de manera real y precisa y, en cualquier caso, sin que induzcan al Comprador a enga&ntilde;o o confusi&oacute;n.</p>
        <p>4.3. Como consecuencia de lo anterior, Sol de Marzo no asume ninguna responsabilidad por la informaci&oacute;n publicada en Sol de Marzo por sus Vendedores, debiendo dirigir cualquier reclamaci&oacute;n directamente a los Vendedores. No obstante, en caso de detectar alg&uacute;n error o inexactitud, rogamos se comunique con nosotros a trav&eacute;s del tel&eacute;fono 91 234 56 78 o de la <a href="/DAW_proyecto_final/templates/dashboard.php?page=messages">secci&oacute;n de mensajes de contacto</a></p>
        <p>4.4. Los precios en Sol de Marzo son fijados por los Vendedores y se muestran en EUROS e incluyen IVA y cualesquiera otros impuestos aplicables. No obstante, lo anterior, es posible que la informaci&oacute;n sobre impuestos pueda variar por cambios en los mismos. Los precios mostrados en Sol de Marzo no incluyen los gastos de transporte, que ser&aacute;n mostrados durante el proceso de compra, antes del pago, conforme a la informaci&oacute;n publicada por los Vendedores.</p>
        <p>4.5. Sol de Marzo&nbsp;se compromete a no permitir ninguna transacci&oacute;n que sea ilegal, o se considere por las marcas de tarjetas de cr&eacute;dito o el banco adquiriente, que pueda o tenga el potencial de da&ntilde;ar la buena voluntad de los mismos o influir de manera negativa en ellos. Las siguientes actividades est&aacute;n prohibidas en virtud de los programas de las marcas de tarjetas: la venta u oferta de un producto o servicio que no sea de plena conformidad con todas las leyes aplicables al Comprador, Banco Emisor, Comerciante, Titular de la tarjeta, o tarjetas.</p>
        <h2>5. Pasos para la compra</h2>
        <p>5.1. El Comprador deber&aacute;:<br /> <br /> a. Navegar por Sol de Marzo&nbsp;e ir a&ntilde;adiendo a su cesta de la compra aquellos productos que desea adquirir<br /> <br /> b. Acceder al carrito de la compra y verificar que desea adquirir todos los productos en &eacute;l incluidos.<br /> <br /> c. Incluir la direcci&oacute;n de env&iacute;o en la que desea recibir su pedido o seleccionarla de entre todas las ya incluidas y confirmar.<br /> <br /> d. Seleccionar el m&eacute;todo de pago y, previa aceptaci&oacute;n de estas Condiciones, pagar. Actualmente, est&aacute;n disponibles los m&eacute;todo de pago mediante tarjeta a trav&eacute;s del TPV de Sol de Marzo, redireccionamiento a la plataforma de Paypal, a trav&eacute;s de Bizum o contra-reembolso.<br /> <br /> e. Realizado el pago, el Comprador recibir&aacute; de Sol de Marzo&nbsp;confirmaci&oacute;n de su aceptaci&oacute;n y, en su caso, del correcto pago.<br /> <br /> f. El pedido habr&iacute;a de ser recibido en el plazo indicado por cada Vendedor en las Condiciones Particulares de cada producto de los que conforman el pedido. Es posible que cada producto de los que conforman el pedido sea recibido en d&iacute;as distintos, pues tanto los Vendedores como las Condiciones Particulares tambi&eacute;n podr&iacute;an serlo.</p>
        <p>5.2. La/s factura/s ser&aacute;/n remitida/s al Comprador por cada Vendedor por el importe del/de los producto/s por &eacute;l enviados. Con la aceptaci&oacute;n de estas Condiciones el Comprador consiente a los Vendedores de los productos que conforman su pedido el env&iacute;o de factura electr&oacute;nica.</p>
        <h2>6. Desistimiento</h2>
        <p>6.1. Sol de Marzo&nbsp;informa al Comprador, para el supuesto de que el Vendedor no le informara en las Condiciones Particulares de su derecho a desistir de la compra o de que no goza de este derecho, de que, salvo excepciones, dispone de catorce d&iacute;as naturales, desde que recibe el &uacute;ltimo de los productos de su pedido para desistir de la compra de alguno de ellos sin necesidad de especificar motivo alguno.</p>
        <p>As&iacute; mismo, el derecho de desistimiento regulado en el presente apartado &uacute;nicamente podr&aacute; ser ejercitado en los casos establecidos por ley y en relaci&oacute;n con los productos adquiridos a trav&eacute;s de la plataforma, conforme a las especificaciones establecidas en los presentes T&eacute;rminos y Condiciones. De conformidad con el art&iacute;culo 103 del Real Decreto Legislativo 1/2007, de 16 noviembre por el que se aprueba el texto refundido de la Ley General para la Defensa de los Consumidores y Usuarios, el derecho de desistimiento no es aplicable cuando se trate de la contrataci&oacute;n de bienes perecederos que pueden deteriorarse o caducar con rapidez.</p>
        <p>6.2. Para ello, antes de que venza el mencionado plazo, deber&aacute; ponerlo en conocimiento del Vendedor enviando, por cualquier medio, el formulario contenido en el&nbsp;<a href="/DAW_proyecto_final/templates/components/info/condiciones-generales-de-compra-anexo.pdf">Anexo a estas Condiciones&nbsp;</a>completado con sus datos o cualquier otra comunicaci&oacute;n en que conste inequ&iacute;vocamente que ejerce su derecho a desistir del contrato, as&iacute; como sobre qu&eacute; productos lo ejerce.</p>
        <p>6.3. El ejercicio del derecho a desistir por su parte supone que el Vendedor, dentro de los 14 d&iacute;as naturales siguientes a aqu&eacute;l en que es informado de que ejerce su derecho a desistir y a trav&eacute;s del mismo medio empleado para el pago (salvo que el Comprador indique lo contrario), proceder&aacute; a devolverle, sin ning&uacute;n coste (salvo los gastos adicionales resultantes de la elecci&oacute;n por parte del Comprador de una modalidad de entrega diferente a la modalidad menos costosa de entrega ordinaria que el Vendedor le ofreciera) las cantidades pagadas por el/los producto/s del/de los que se desiste.</p>
        <p>6.4. Ejercido por el Comprador su derecho a desistir, deber&aacute; devolver al Vendedor el/los producto/s del/ de los que desiste, a m&aacute;s tardar, en el plazo de 14 d&iacute;as naturales desde que comunic&oacute; su decisi&oacute;n de desistir. Ser&aacute; el Comprador quien deba asumir los costes directos de la devoluci&oacute;n de los bienes. Los productos deber&aacute;n encontrarse en el mismo estado en que fueron entregados.</p>
        <h2>7. Garant&iacute;a legal del Vendedor</h2>
        <p>Sin perjuicio de lo que el Vendedor indique, Sol de Marzo informa al Comprador de que dispone de una garant&iacute;a legal de conformidad de dos a&ntilde;os desde la entrega, conforme a lo establecido en el Real Decreto Legislativo 1/2007, de 16 de noviembre, por el que se aprueba el Texto Refundido de la Ley General para la Defensa de los Consumidores y Usuarios y otras leyes complementarias, en virtud de la cual los productos adquiridos.</p>
        <h2>8. Obligaciones del Comprador</h2>
        <p>8.1. La principal obligaci&oacute;n del Comprador es la de abonar a Sol de Marzo el precio de los productos que conforman su pedido al formalizar las presentes Condiciones.</p>
        <p>8.2. Asimismo, el Comprador abonar&aacute; los gastos de env&iacute;o que el Vendedor de cada producto haga constar durante el proceso de compra.</p>
        <p>8.3. En general, el Comprador se obliga a actuar de buena fe y de forma leal para con Sol de Marzo y con cada Vendedor del que adquiriera productos a trav&eacute;s de Sol de Marzo.</p>
        <p>8.4. Adem&aacute;s, las siguientes actividades tambi&eacute;n est&aacute;n prohibidas expl&iacute;citamente:<br /> -Venta de bebidas alcoh&oacute;licas a menores de 18 a&ntilde;os</p>
        <h2>9. Valoraci&oacute;n de Vendedores</h2>
        <p>9.1. Cuando un Comprador hubiera recibido un pedido, se habilitar&aacute; en su perfil de usuario en Sol de Marzo la posibilidad de valorar al Vendedor y los productos adquiridos de &eacute;ste. En particular, el Comprador podr&aacute; valorar:<br /> <br /> a. La satisfacci&oacute;n con la compra, en general.<br /> <br /> b. La calidad.<br /> <br /> c. El precio.<br /> <br /> d. En su caso, el sabor.</p>
        <p>9.2. Siempre que un Comprador vaya a valorar a un Vendedor, deber&aacute;:<br /> <br /> a. Respetar la legislaci&oacute;n aplicable, la moral y las buenas costumbres generalmente<br /> <br /> aceptadas, el orden p&uacute;blico y las presentes Condiciones o cualesquiera otras resultaren aplicables.<br /> <br /> b. Emitir &uacute;nicamente opiniones y comentarios l&iacute;citos y veraces, ajustados a la tem&aacute;tica y al contenido de cada art&iacute;culo.<br /> <br /> c. Conferir a Sol de Marzo licencia tan amplia como en derecho se requiera para la publicaci&oacute;n de los textos en Internet.<br /> <br /> d. Abstenerse de introducir links o enlaces a terceros que contengan cualquiera de los anteriores contenidos, publicidad il&iacute;cita, enga&ntilde;osa o desleal, virus, troyanos o cualquier otro material o software que pueda da&ntilde;ar o alterar el funcionamiento de equipos o sistemas inform&aacute;ticos.<br /> <br /> e. Abstenerse de enviar contenidos o enlaces difamatorios, injuriosos, ofensivos, insultantes, racistas, obscenos, amenazadores o discriminatorios; as&iacute; como comerciales, promocionales o publicitarios.<br /> <br /> f. Asumir cualquier responsabilidad que se derive de haber dejado un comentario o valoraci&oacute;n a un Vendedor o a sus productos, dejando completamente indemne a Sol de Marzo en este sentido.<br /> <br /> g. Abstenerse de utilizar el sistema de valoraci&oacute;n para favorecer o perjudicar injustificadamente y de mala fe a un Vendedor.</p>
        <p>9.3. Sol de Marzo no supervisa los comentarios ni las valoraciones de los Compradores, si bien se reserva el derecho a eliminarlos, total o parcialmente, si adquiere conocimiento de que con ellos se est&aacute; vulnerando alguna de las anteriores normas o si lo requiriese la autoridad.</p>
        <h2>10. Servicio de reclamaciones y quejas hacia un Vendedor</h2>
        <p>10.1. Sol de Marzo pone a tu disposici&oacute;n la&nbsp;<a href="/DAW_proyecto_final/templates/dashboard.php?page=feedback">secci&oacute;n de feedback&nbsp;<strong>(clic aqu&iacute;)</strong></a>&nbsp;a efectos de que remita, a trav&eacute;s de la misma, cualesquiera reclamaciones o quejas tuviera en relaci&oacute;n con alg&uacute;n Vendedor, a Sol de Marzo.</p>
        <p>10.2. Sol de Marzo tramitar&aacute; las solicitudes del Comprador, contest&aacute;ndole cuanto antes, dentro de las posibilidades. Si bien Sol de Marzo no puede garantizar la satisfacci&oacute;n de la misma, se esforzar&aacute; por atenderla.</p>
        <h2>11 Garant&iacute;as y responsabilidades</h2>
        <p>11.1. Sol de Marzo realiza sus mayores esfuerzos para que Sol de Marzo se encuentre disponible a efectos de que se formalicen correctamente todas las transacciones que interesan al Comprador. No obstante, no garantiza que la compra de productos pueda ser formalizada en todo momento, pues, por determinadas circunstancias que escapan al control de Sol de Marzo, la disponibilidad de Sol de Marzo y su funcionamiento podr&iacute;an verse comprometidos.</p>
        <p>11.2. Sol de Marzo act&uacute;a como un mero intermediario entre el Comprador y el Vendedor. En este sentido, Sol de Marzo declina toda responsabilidad respecto de:<br /> <br /> a. La calidad, conformidad y utilidad de los servicios prestados o de los bienes recibidos.<br /> <br /> b. La correcta recepci&oacute;n de los bienes objeto de pedido.<br /> <br /> c. Los da&ntilde;os personales o materiales que pudieran derivarse del disfrute de los servicios o del uso de los bienes.</p>
        <p>11.3. El Comprador ser&aacute; el &uacute;nico responsable de los da&ntilde;os y perjuicios que se deriven como consecuencia de haber incurrido en errores durante el proceso de compra o de no cumplir con cualesquiera requisitos aqu&iacute; dispuestos o dispuestos en las Condiciones Particulares impuestas por los Vendedores, o contenidos en cualesquiera otras condiciones que resultaran aplicables.</p>
        <p>11.4. El Comprador reconoce y acepta que cualesquiera fotograf&iacute;as mostradas por los Vendedores en Sol de Marzo son ejemplificativas, de forma que los bienes o los servicios podr&iacute;an no corresponderse &iacute;ntegramente con las im&aacute;genes mostradas en Sol de Marzo.</p>
        <p>11.5. En cualquier caso, la responsabilidad que asume Sol de Marzo frente al Comprador en ning&uacute;n caso incluye el lucro cesante y se limitar&aacute;, en todo caso, como m&aacute;ximo y por cualquier concepto, al importe total percibido por Sol de Marzo.</p>
        <h2>12. Indemnizaci&oacute;n</h2>
        <p>12.1. Cualquier incumplimiento de estas Condiciones Generales de Compra por parte del Comprador puede suponer para Sol de Marzo da&ntilde;os y perjuicios. Si as&iacute; ocurriera, cualquier tipo de p&eacute;rdidas y costes (como puedan ser los honorarios de abogados y procuradores), el Comprador estar&aacute; obligado a resarcir a Sol de Marzo.</p>
        <p>12.2. Asimismo, si por los incumplimientos del Comprador se generaran cualquier tipo de reclamaciones o procedimientos contra Sol de Marzo, aqu&eacute;l dejar&aacute; indemne a &eacute;ste, pudi&eacute;ndole ser reclamado cualquier gasto, coste, da&ntilde;o o perjuicio derivado de sus acciones.</p>
        <h2>13. Protecci&oacute;n de datos</h2>
        <p>Sol de Marzo cuenta con una Pol&iacute;tica de Privacidad que puede conocer haciendo clic&nbsp;<a href="/DAW_proyecto_final/templates/components/info/lopd.php">aqu&iacute;.</a></p>
        <h2>14. Idioma</h2>
        <p>14.1. El idioma aplicable a estas Condiciones Generales de Compra y en que las mismas se formalizan es el espa&ntilde;ol. Si se han ofrecido versiones de tales Condiciones en otros idiomas ha sido por mera cortes&iacute;a, para la comodidad del Comprador, y &eacute;ste acepta expresamente que las mismas se regir&aacute;n por su versi&oacute;n en espa&ntilde;ol.</p>
        <p>14.2. Si hubiera alguna contradicci&oacute;n entre lo que dice la versi&oacute;n en espa&ntilde;ol de tales Condiciones y lo que dice su traducci&oacute;n, en todo caso prevalecer&aacute; la versi&oacute;n en espa&ntilde;ol.</p>
        <h2>15. Salvaguarda e interpretaci&oacute;n de las Condiciones</h2>
        <p>15.1. Las presentes Condiciones Particulares existentes, constituyen un acuerdo &uacute;nico entre el Comprador y Sol de Marzo.</p>
        <p>15.2. En caso de que alguna disposici&oacute;n de las presentes Condiciones fuera considerada ilegal, inv&aacute;lida manera tal que se pueda interpretar como ejecutable y efectiva del modo m&aacute;s pr&oacute;ximo posible a la intenci&oacute;n original de la disposici&oacute;n.</p>
        <p>15.3. La no exigencia del cumplimiento estricto de alguno de los t&eacute;rminos de estas Condiciones no supone ni puede interpretarse como una renuncia por parte de Sol de Marzo a exigir su cumplimiento en sus estrictos t&eacute;rminos en el futuro.</p>
        <p>15.4. La declaraci&oacute;n de nulidad de alguna o algunas de las cl&aacute;usulas establecidas en las presentes Condiciones Generales de Compra por parte de Autoridad competente no perjudicar&aacute; la validez de las restantes.</p>
        <p>15.5. Si la sustituci&oacute;n deviniese imposible y la cl&aacute;usula fuese esencial para las Condiciones Generales de Compra, a juicio de la parte perjudicada por su eliminaci&oacute;n, &eacute;sta podr&aacute; optar por la resoluci&oacute;n de las Condiciones.</p>
        <h2>16. Legislaci&oacute;n y fuero</h2>
        <p>16.1. Las relaciones entre Sol de Marzo y los Compradores se rigen por la legislaci&oacute;n y jurisdicci&oacute;n espa&ntilde;olas.</p>
        <p>16.2. Sol de Marzo y el Comprador, con renuncia expresa a cualquier otro fuero que pudiera corresponderles, se someten al de los Juzgados y Tribunales del domicilio del Comprador para la resoluci&oacute;n de conflictos relativos a estas Condiciones Generales de Compra y cualquiera de sus Condiciones Particulares. En el caso de que el Comprador tenga su domicilio fuera de Espa&ntilde;a, Sol de Marzo y el Comprador se someten, con renuncia expresa a cualquier otro fuero, a los juzgados y tribunales de Espa&ntilde;a.</p>
    </div>
<?php include_once(__DIR__ . '/../footer.php'); ?>