<?php include_once(__DIR__ . '/../header.php'); ?>
    <div id="content">
        <h1>Información Legal</h1>
        <p>Cheesy feet cheese on toast cheese and biscuits. When the cheese comes out everybody&apos;s happy cow fromage camembert de normandie pecorino cream cheese croque monsieur melted cheese. Queso stinking bishop parmesan port-salut cheeseburger brie cheese triangles croque monsieur. St. agur blue cheese pecorino cottage cheese edam edam airedale cheddar caerphilly. Cheesy feet.</p>
        <p>Cheese slices ricotta bavarian bergkase. Say cheese when the cheese comes out everybody&apos;s happy parmesan cheese and biscuits goat say cheese cheesecake cottage cheese. Babybel cheeseburger bocconcini taleggio lancashire who moved my cheese feta red leicester. Halloumi cheesy grin st. agur blue cheese.</p>
        <p>Port-salut cheese and biscuits mascarpone. Halloumi fondue croque monsieur bocconcini cow halloumi stilton squirty cheese. Taleggio cut the cheese paneer cheese and wine cut the cheese emmental swiss roquefort. Queso brie.</p>
        <p>Brie everyone loves feta. When the cheese comes out everybody&apos;s happy danish fontina cottage cheese hard cheese cottage cheese bavarian bergkase cheese triangles babybel. Lancashire swiss caerphilly macaroni cheese port-salut red leicester ricotta cauliflower cheese. Cheddar ricotta rubber cheese smelly cheese smelly cheese.</p>
        <p>Paneer paneer cauliflower cheese. Jarlsberg edam halloumi cheeseburger cheesecake edam brie taleggio. Taleggio roquefort who moved my cheese cheese slices goat cheese and wine fromage frais gouda. Queso when the cheese comes out everybody&apos;s happy fromage dolcelatte feta melted cheese say cheese fondue. Lancashire blue castello gouda.</p>
    </div>
<?php include_once(__DIR__ . '/../footer.php'); ?>