<?php include_once(__DIR__ . '/../header.php'); ?>
    <div id="content">
        <h1>Pol&iacute;tica de Privacidad</h1>
        <p>La presente Pol&iacute;tica de Privacidad regula la obtenci&oacute;n y tratamiento de los datos de car&aacute;cter personales que facilite como consecuencia de la utilizaci&oacute;n de la web Sol de Marzo (en adelante, Sol de Marzo), por parte de su titular Sol de Marzo, S.L. (en adelante, Sol de Marzo).</p>
        <p>Sus datos personales se incorporar&aacute;n a un fichero responsabilidad de Sol de Marzo, para su tratamiento, automatizado y no automatizado, de conformidad con las siguientes finalidades:</p>
        <p>1. Al registrarse en Sol de Marzo se le requerir&aacute; de la aportaci&oacute;n de unos datos identificativos y de contacto necesarios para tramitar su registro y habilitar los servicios ofrecidos en la web, entre los que se incluyen poder llevar una lista de productos favoritos, gestionar pedidos, etc.</p>
        <p>2. Si contacta con Sol de Marzo a trav&eacute;s de los formularios destinados a tal efecto o por cualquier otro medio de contacto, se le requerir&aacute; informaci&oacute;n identificativa y de contacto para poder tramitar su consulta y atender a la misma.</p>
        <p>3. Por el uso que haga de Sol de Marzo podr&aacute; aportar diversa informaci&oacute;n personal sobre sus gustos y preferencias, la cual ser&aacute; empleada por Sol de Marzo para adaptar la web a sus preferencias y ofrecerle, a trav&eacute;s de la propia web o no, informaci&oacute;n de su inter&eacute;s.</p>
        <p>4. Asimismo, ser&aacute; necesario que nos facilite sus datos bancarios, tarjetas de cr&eacute;dito/d&eacute;bito o informaci&oacute;n sobre su cuenta de Paypal o servicio similar, as&iacute; como ciertos datos adicionales de contacto, a efectos de gestionar los cobros y colaborar con los Vendedores en la gesti&oacute;n de sus pedidos.</p>
        <p>5. En relaci&oacute;n a las Cookies, Sol de Marzo puede disponer de tecnolog&iacute;a para la implantaci&oacute;n de archivos denominados cookies en el terminal en que haya instalado la web. Podr&aacute; bloquear o deshabilitar las cookies en cualquier momento a trav&eacute;s de las opciones de configuraci&oacute;n de Sol de Marzo. Si desea m&aacute;s informaci&oacute;n al respecto, puede consultar nuestra Pol&iacute;tica de Cookies&nbsp;<a href="/DAW_proyecto_final/templates/components/info/cookies.php">aqu&iacute;.</a></p>
        <p>6. Por otro lado, al aceptar la presente Pol&iacute;tica de Privacidad otorga a Sol de Marzo su consentimiento para el env&iacute;o de publicidad propia acerca de novedades y productos, salvo que se hubiera opuesto expresamente a ello en el momento de facilitarnos sus datos.</p>
        <p>No obstante, puede retirar dicho consentimiento en cualquier momento poni&eacute;ndolo en conocimiento de Sol de Marzo, a trav&eacute;s de un escrito a trav&eacute;s de la&nbsp;<a href="/DAW_proyecto_final/templates/dashboard.php?page=messages">secci&oacute;n de mensajes.</a></p>
        <p>A trav&eacute;s de las herramientas ofrecidas en Sol de Marzo podr&aacute; modificar los datos relativos a su perfil o cancelar su cuenta en la web. Tambi&eacute;n puede comunicarnos cualquier modificaci&oacute;n por escrito o solicitar su baja a trav&eacute;s del&nbsp;<a href="https://d.docs.live.net/DAW_proyecto_final/templates/dashboard.php?page=messages">secci&oacute;n de mensajes.</a></p>
    </div>
<?php include_once(__DIR__ . '/../footer.php'); ?>